### ISSUE TITLE
Link creation does not work

### ISSUE THREAD

**Issue by bluepuma77** [friendofsvelte/tipex#9]
When using the example from the docs "Insert a set of buttons" ([link](https://tipex.pages.dev/customization)):
```
import {Utility} from "@friendofsvelte/tipex";
<Tipex htmlContent={htmlContent}>
    <svelte:fragment slot="utilities">
        <Utility/>
    </svelte:fragment>
</Tipex>
```
saving the link does not work, throws exception:
```
[Tipex.svelte:61:4](http://localhost:5173/node_modules/@friendofsvelte/tipex/dist/tipex/Tipex.svelte)
Uncaught TypeError: editorsParent is null
    onFocusChange Tipex.svelte:61
    instance4 Tipex.svelte:65
```

And how can the link button be left aligned with the other buttons?

**Comment by Bishwas-py** [comment]
@bluepuma77 I tried to recreate the scene:
![image](https://github.com/friendofsvelte/tipex/assets/42182303/95c4915a-c3ab-467c-a0da-cbb22217ba56)
But, I was unable to do so:
![image](https://github.com/friendofsvelte/tipex/assets/42182303/bd124963-f85a-423b-867d-47603bc1b1f5)
![image](https://github.com/friendofsvelte/tipex/assets/42182303/3f27afe3-26b0-4e9d-b349-cad60721f225)
![image](https://github.com/friendofsvelte/tipex/assets/42182303/96f6dbc4-61aa-4ac0-8ec5-5a32a5ebeb9a)

It is working. Can you help me recreate it? I think the issue might be because of version, current version is: `0.0.1-act.3`

**Comment by bluepuma77** [comment]
Here is a Stackblitz [link](https://stackblitz.com/edit/sveltejs-kit-template-default-agzzrq?description=Tipex&file=src%2Froutes%2F%2Bpage.svelte). I can select text and click link button, enter a link, but then neither `return` nor `Save` close the dialog.

**Comment by bluepuma77** [comment]
Ah, never mind, it will only accept a valid URL, but there is no error indication or message. Sorry.
